apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - karpenter-values.yaml
  - karpenter-config.yaml
  - nvidia-device-plugin.yaml
  - efa-device-plugin.yaml
  - aws-lb-controller.yaml
  - external-dns.yaml
  - adot-collector.yaml
  - dcgm-exporter.yaml
