apiVersion: batch/v1
kind: CronJob
metadata:
  name: osmo-secrets-sync
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: osmo-secrets-sync
          restartPolicy: OnFailure
          containers:
            {{- include "osmo-secrets.sync-container" . | nindent 12 }}
