apiVersion: batch/v1
kind: Job
metadata:
  name: osmo-secrets-sync-init
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: osmo-secrets-sync
      restartPolicy: OnFailure
      containers:
        {{- include "osmo-secrets.sync-container" . | nindent 8 }}
