apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-cluster
  namespace: {{ .Release.Namespace }}
  {{- if .Values.rayRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.rayRoleArn | quote }}
  {{- end }}
